spring:
  config:
    activate:
      on-profile: prod

server:
  error:
    include-message: never
    include-stacktrace: never
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}
        same-site: ${SESSION_COOKIE_SAME_SITE:None}

